config commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -329,9 +329,9 @@ jobs:
             echo "${API_URL}"
             if curl "${API_URL}/api/status" | grep "ok"
             then
-                Return 0
+                exit 0
             else
-                Return 1
+                exit 1
             fi
       - run:
           name: Frontend smoke test.
@@ -409,16 +409,16 @@ jobs:
 workflows:
   default:
     jobs:
-      - build-frontend
-      - build-backend
-      - test-frontend:
-           requires: [build-frontend]
-      - test-backend:
-           requires: [build-backend]
-      - scan-backend:
-            requires: [build-backend]
-      - scan-frontend:
-            requires: [build-frontend]
+    #   - build-frontend
+    #   - build-backend
+    #   - test-frontend:
+    #        requires: [build-frontend]
+    #   - test-backend:
+    #        requires: [build-backend]
+    #   - scan-backend:
+    #         requires: [build-backend]
+    #   - scan-frontend:
+    #         requires: [build-frontend]
       - deploy-infrastructure: 
             requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       - configure-infrastructure:
@@ -431,10 +431,10 @@ workflows:
             requires: [run-migrations]
       - smoke-test:
             requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-            requires: [smoke-test]
-      - cleanup:
-            requires: [cloudfront-update]                
+    #   - cloudfront-update:
+    #         requires: [smoke-test]
+    #   - cleanup:
+    #         requires: [cloudfront-update]                
 
 
 
